version: 2.1

orbs:
  rn: react-native-community/react-native@1.2.1

jobs:
  check-yarn-version:
    executor: rn/linux_js
    steps:
      - run:
          name: "Check YARN version"
          command: |
            yarn --version
  check-npm-version:
    executor: rn/linux_js
    steps:
      - run:
          name: "Check NPM version"
          command: |
            npm --version

workflows:
  test:
    jobs:
      - check-yarn-version
      - check-npm-version