version: 2.1

orbs:
  rn: react-native-community/react-native@1.2.1

jobs:
  check-yarn-version:
    executor: rn/linux_js
    steps:
      - checkout
      - run:
          name: "List dir contents"
          command: |
            pwd && ls -al
      - run:
          name: "Install Yarn dependencies"
          command: |
            cd abc/ && yarn install
  check-npm-version:
    executor: rn/linux_js
    steps:
      - run:
          name: "Check NPM version"
          command: |
            npm --version

workflows:
  test:
    jobs:
      - check-yarn-version
      - check-npm-version